# -*- coding: utf-8 -*-
"""112148

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X7Mr3tvPG-s2BMALwXpWCBb-E3ta_7bf
"""

a = int(input())
b = a // 100
c = (a // 10) % 10
d = a % 10
print(b, c, d)