# -*- coding: utf-8 -*-
"""2937

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wHMc9cDWa4ACNths7p-xnMezTYwnii64
"""

a = int(input())
print('The next number for the number ', a, ' is ', a + 1, '.', sep = '')
print('The previous number for the number ', a, ' is ', a - 1, '.', sep = '')