# -*- coding: utf-8 -*-
"""3465

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lj0MI7icO-zEmF9anT7jpyzFAvuRfDER
"""

a = int(input())
print(((a // 2) + 1) * 2)