# -*- coding: utf-8 -*-
"""3479

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NXS3y06x7Ju1Skzr1p77_579NgFJp9Cc
"""

a = int(input())
b = int(input())
if a % b == 0 or b % a == 0:
  print(1)
else:
  print(2)
